:toc:

[[discussion]]
== Discussion

// NOTE
this approach allows us to keep using the already existing tool supports, such as syntax highlighting plugins, refactoring feature of editors, CLI tools to manipulate the data, and other utilities.
For application developers, it is also beneficial because burdens to simplify their configuration notations will be removed.
Users will be able to take care of it by themselves using inheritances and reusable node value computations.
Only in case they want to uniform how such configurations should be written across their users, they can bundle standard **JSON{plus}{plus}** files which define reasonable default values and reusable logics for the default values of their product.

=== Interpretation of Results

(t.b.d.)

=== Implications

(t.b.d.)

=== Limitations

Features beyond JSON::
In case a notation has a feature, which cannot be represented in **JSON**, this approach requires extra treatment.
For example, **YAML** allows to define entries with the same key multiple times, which is not valid in **JSON**.
In such cases, we will need to introduce a convention that interprets it into **JSON**, and converts it back to **YAML**, safely.

Application-level Syntax-sugars::
An application sometimes defines its own syntax on top of its data notation for user's convenience.
We expect such a syntax to be simplified and uniformed by applying our approach.
However, this benefit was not examined in this study.
